[package]
name = "gtk_demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.14.0"
glib = "0.14.0"
gio = "0.14.0"
cascade = "1.0.0"